feat: add ErrorWithDetail
go-fuego/fuego pull request #228
Opened 2024-11-20 17:08 UTC by dylanhitt

Closes #225

Adds `ErrorWithDetail` interface to allow for response of detail. This is similar to the older with Info. The motivation for this is the fact that we use the detail option in the [`slog.Error`](https://github.com/go-fuego/fuego/blob/main/errors.go#L148) in the default error handler as well as in the [`HTTPError.Error()` func](https://github.com/go-fuego/fuego/blob/main/errors.go#L43). Maybe we should default into something as well in the case where the user doesn't supply it.

If this is acceptable I will update the docs now as well.

2024-11-21 14:01 UTC, dylanhitt commented
@EwenQuim should I update the docs?

2024-12-05 22:15 UTC, EwenQuim approved these changes

2024-12-06 01:25 UTC, dylanhitt commented
I’ll update the docs as well tomorrow.

2024-12-06 19:03 UTC, dylanhitt commented
@EwenQuim if you don't mind looking at the doc updates that would be great. I'm not the best writer.

2024-12-06 19:11 UTC, EwenQuim requested changes

2024-12-06 19:12 UTC, EwenQuim commented
> I'm not the best writer.

If you're not the best writer, then I'm a terrible one. The doc update is great!

2024-12-06 19:49 UTC, dylanhitt commented on examples/basic/main.go
Done

2024-12-09 16:38 UTC, dylanhitt commented
@EwenQuim you mind taking another look. Trying to clear my backlog

2024-12-09 17:14 UTC, EwenQuim approved these changes

2024-12-09 17:15 UTC, EwenQuim commented
Nice, thanks!

Yes don't worry, Fuego is very active at the moment. But that's a good sign!

We'll be taking a break during winter holidays.

2024-12-09 17:17 UTC, merged