Optimize memory alignment by reordering fields
go-fuego/fuego pull request #299
Opened 2024-12-21 10:27 UTC by EwenQuim

Just a dumb PR to reduce memory usage and improve performance by simply realigning struct fields.  
I can't believe this has to be done manually—obviously, the compiler should handle it.  

This also enables all govet linters in the CI (including the `fieldalignment` check).  

Maybe we can wait for #285 to see the improvement or lack thereof.

2024-12-21 12:50 UTC, ccoVeille approved these changes

2024-12-21 22:28 UTC, dylanhitt approved these changes
TIL

2025-01-07 19:01 UTC, dylanhitt commented on .golangci.yml
> +
nit pick extra space.

2025-01-07 19:03 UTC, dylanhitt commented
> What do you think about the Makefile change @ccoVeille @dylanhitt ? It makes make fmt and then make optimize struct memory usage automatically!

Yes I like it. Will say maybe we shouldn't be installing things on people machines so implicitly. I tend to use like a `make init` or `make deps`. For instance I would `which` like how you're doing and then if fail i would print a statement to the user saying x needs to be installed and `make init` will do it for you.

2025-01-07 19:47 UTC, ccoVeille requested changes
I don't think anything like this is needed.

You are building an API service, with OpenAPI features.

Here it's about optimizing bytes of memory on a framework, that stay still between 2 API calls.

If someone needs memory efficient solution, I'm afraid to say they will never use a framework like fuego, I mean any framework.

I would like to discourage you to go in this direction that is making the struct less readable.

For me it's pure "oh it's good feature we should try"

So unless you have a benchmark that shows a change of at least 20% I'm term of speed or memory consumption, I would say NOGO

2025-01-07 19:47 UTC, ccoVeille commented on Makefile
> +	which betteralign || go install github.com/dkorunic/betteralign/cmd/betteralign@latest
Is there so much differences with govet fieldalignment that you want to use this fork?

2025-01-07 20:02 UTC, dylanhitt commented
wait a minute what?

> Here it's about optimizing bytes of memory on a framework, that stay still between 2 API calls.

A fuego context and fuego response is gonna be created on every API call to some using this framwork? If i have an API with 1000 concurrent calls (which I do). You're allocating a context for all 1000 api calls.

2025-01-07 20:03 UTC, dylanhitt commented
Like this struct alone could be created `10,000` times: https://github.com/go-fuego/fuego/pull/299/files#diff-c4dd82978a1a49bcd620aff72208bbd8114f09341d701e188c247ce3e3511117R126

2025-01-07 20:37 UTC, ccoVeille commented
I'm sorry if my reply 

Is fuego highly optimized for ultra fast performance? I cannot tell.

The recent PR I see are about adding feature, not about looking for insane performance

I'm not saying the changes in this PR have no consequences at all. It's proven, known, documented, there are linters about it.

My point is "are they noticeable?"

But will it has a consequence of server bills? A noticeable consequence on performance?

What I can see is the consequence on readability

You talked about an allocatio on every http calls, but what is it compared the cost in memory of receiving and returning the HTTP messages ?

For me such optimization should be on compiler side. But it isn't unfortunately.

Also, such optimization provides an easy fix for small memory optimization. But this is far from being a way to improve a framework performance.

It's very good optimization when dealing with millions of data to sort in memory, yes.

But here, I'm doubtful. That's why I'm asking for benchmarks.

If you think the readability is still OK after such "optimization", why not.

2025-01-07 20:43 UTC, dylanhitt commented
> You talked about an allocatio on every http calls, but what is it compared the cost in memory of receiving and returning the HTTP messages ?

Again I'm not really understanding your point here either. This would be entirely on the user using fuego. We won't know their body or requestbody it's up to them to optimize their own structs. The best we can do is optimize what we can control when someone wants to squeak out some performance where they can.

2025-01-07 20:46 UTC, dylanhitt commented
And to answer readability. No I don't really see an impact/maintenance over grouping struct fields. If we really cared so much about this I would much rather focus on better commits/concise PRs than I would the grouping of the struct. Git can at least tell a story.

2025-01-07 20:56 UTC, ccoVeille commented
I apparently fail to explain why I think (hypothesis) it will have quite no consequences on the end user.

At the same time, I think that I'm getting you upset or disappointed, because of what I said, I'm sorry about that.

Also, you think it could (here another hypothesis) have noticeable consequences for the performance.

I conceeded there will be improvement, my point is about the fact I don't think the could be noticed.

I can be wrong, and it won't be a problem to me.

I asked for a benchmark, because I would like to get something that can be checked/compared.

Maybe @EwenQuim can tell what he thinks about it. Maybe he made a benchmark

2025-01-07 21:44 UTC, dylanhitt commented
I'm not upset or disappointed. I'm just not understanding the point being made. I don't know what

> Here it's about optimizing bytes of memory on a framework, that stay still between 2 API calls.

When I read that it sounds like you're saying is that "the code in fuego really only is responsible for 2 API calls so why optimize"? 

I do agree that the majority of the optimization is really dependent on our users. 

Fuego specifically `fuego.Server` really doesn't do much past creating a `netHttpContext` for every api call in regards to memory. However that is struct is allocated every time a fuego server route is used. So let's take our current benchmark on `main`. Specifically `BenchmarkContext_Body/valid_JSON_body-10` and `BenchmarkRequest/fuego_server_and_fuego_post-10` main gives us

```
BenchmarkContext_Body/valid_JSON_body-10                  389785              3055 ns/op            7258 B/op         32 allocs/op
BenchmarkRequest/fuego_server_and_fuego_post-10           207608              5718 ns/op            8273 B/op         69 allocs/op
BenchmarkRequest/fuego_server_and_std_post-10             307184              3850 ns/op            7489 B/op         46 allocs/op
BenchmarkRequest/std_server_and_std_post-10               391288              3054 ns/op            7137 B/op         29 allocs/op
``` 

vs this branch

```
BenchmarkContext_Body/valid_JSON_body-10                  400556              3012 ns/op            7242 B/op         32 allocs/op
BenchmarkRequest/fuego_server_and_fuego_post-10           207830              5660 ns/op            8257 B/op         69 allocs/op
BenchmarkRequest/fuego_server_and_std_post-10             300900              3814 ns/op            7489 B/op         46 allocs/op
BenchmarkRequest/std_server_and_std_post-10               371756              3028 ns/op            7137 B/op         29 allocs/op
```

So 16 Bytes per request.

2025-01-08 09:34 UTC, ccoVeille commented
Thanks for doing the benchmark.

2025-01-08 10:00 UTC, EwenQuim commented
Don’t worry @ccoVeille, everything is all right!

I understand this approach might be cumbersome for readability in most cases, so I’ll remove the PR and the linter.

However, it still makes sense to optimize memory usage for certain structs, especially `netHttpContext`, since it’s used on every request and remains hidden from the user’s perspective.

2025-01-08 10:05 UTC, EwenQuim commented on Makefile
> +	which betteralign || go install github.com/dkorunic/betteralign/cmd/betteralign@latest
Yes, there was the -fix option that worked!

But I'm removing this from the CI

2025-01-08 11:30 UTC, merged