re-implementing default logging middleware
go-fuego/fuego pull request #313
Opened 2024-12-26 10:45 UTC by jwtly10

This PR implements a simplified default logging middleware, taking on feedback from #303.

These changes simplify #303 and just provides default req/res logging, with options to disable either. Rather than supporting custom logging functions, users who need custom logging can just implement their own mw.

I see some of these use cases:
1. Use default middleware entirely
2. Disable fully/partially disable req/res logging
3. Disable and implement their own logging middleware
4. Use our middleware but override logging funcs

After thinking about how to do this, supporting case 4 does seems unnecessary and more complex that it needs to be - for users needing custom logging it would be cleaner to just implement their own.

Note: Some tests are failing for now due to some golden files not expecting this new middleware by default.

2024-12-26 11:32 UTC, EwenQuim requested changes
Very good PR!

Looking very close to what I expected, thank you very much.

I'd let the possibility for users to provide their own requestId, that's a really common use case. Just add a `func() string` in LoggingConfig :)

Thank you again!

2024-12-26 11:32 UTC, EwenQuim commented on default_middlewares.go
> +func wrapResponseWriter(w http.ResponseWriter) *responseWriter {
`newResponseWriter` to keep Go conventions please

2024-12-26 11:32 UTC, EwenQuim commented on default_middlewares.go
> +				requestID = uuid.New().String()
Introducing a new lib?

`go mod tidy` please

2024-12-26 11:33 UTC, EwenQuim commented
Also, I'd add some tests with `slogassert`. There are some test existing in the codebase that you can mimic.

2024-12-26 14:04 UTC, dylanhitt commented on default_middlewares.go
> +	slog.Info("outgoing response",
Since the Request log is debug. It's probably useful to include `"remote_addr", r.RemoteAddr,` here as well.

2024-12-26 14:15 UTC, dylanhitt requested changes

2024-12-26 14:15 UTC, dylanhitt commented on default_middlewares.go
> +	DisableRequest  bool // If true, request logging is disabled
Place comments above for readability if you don't mind 😄

2024-12-26 15:59 UTC, jwtly10 commented
The only thing I haven't addressed yet is failing tests due to including the new mw in open api docs:

``` go
 expected: "#### Controller: \n\n`github.com/go-fuego/fuego_test.helloWorld`\n\n---\n\ntest description"
 actual  : "#### Controller: \n\n`github.com/go-fuego/fuego_test.helloWorld`\n\n#### Middlewares:\n\n- `github.com/go-fuego/fuego.NewServer.defaultLoggingMiddleware.func16`\n\n---\n\ntest description"
```


./examples/petstore/lib/server_test.go: (I guess this would be best fixed with simple golden file update)

openapi_operations_test.go/options_test.go

I'm not sure what the best way to approach this is for these tests. I guess 2 options off the top of my head are 
1. disable the middleware for these tests 
2. update all the tests to handle this default case of having middleware attached as standard (will also need to change defaultLoggingMiddleware from being an anonymouse function to stop `.func16` showing in docs)

Any other ideas?

2024-12-26 16:49 UTC, EwenQuim commented
Please update the tests with `make golden-update`. The petstore example is an example of Fuego offers out-of-the-box, so it makes sense that the middleware is registered and shown

2024-12-26 17:01 UTC, EwenQuim commented
> will also need to change defaultLoggingMiddleware from being an anonymouse function to stop .func16 showing in docs

Yes and we need a goodNaming. I suggest `defaultFuegoLogger`? @dylanhitt any idea? If @jwtly10 you have a better idea, don't hesitate :)

2024-12-26 18:11 UTC, jwtly10 commented
@EwenQuim thanks for the feedback. defaultLogger makes sense for now. I guess it can be changed in future if needed.

Changes have been made, all tests are now passing :)

2024-12-26 18:29 UTC, dylanhitt commented
On mobile, can you send a picture of the way it looks in stoplight?

2024-12-26 18:42 UTC, jwtly10 commented
@dylanhitt Not sure what you mean? Do you mean how the open api spec renders when it has this middleware? (using stoplight on mobile?)

2024-12-26 18:57 UTC, dylanhitt commented
Oh no, the screenshot is what I needed. Thank you. I like this

2024-12-29 16:48 UTC, dylanhitt approved these changes

2024-12-29 16:48 UTC, dylanhitt approved these changes

2024-12-29 16:53 UTC, dylanhitt commented
I believe @EwenQuim request changes have been addressed. This closes #265

Thank you for the work @jwtly10! We appreciate it.

Cheers

2024-12-29 16:53 UTC, merged