refactor: move accept header form mux to server options
go-fuego/fuego pull request #324
Opened 2024-12-30 05:11 UTC by ekumamatthew

refactor: move accept header form mux to server options

2024-12-30 09:37 UTC, EwenQuim requested changes
Thank you for this PR! 🙏🏼

2024-12-30 09:37 UTC, EwenQuim commented on server.go
> +			func(r *BaseRoute) {
We have an option `OptionHeader` that you can use !

2025-01-09 14:18 UTC, EwenQuim commented
Fixes #266

2025-01-10 17:00 UTC, dylanhitt commented on server_test.go
>  	require.Equal(t, document.Paths.Find("/").Get.Parameters[0].Value.Name, "Accept")
Not your change, but we may want to check if `require.NotNil(t, document.Paths.Find("/").Get.Parameters[0].Value)`

Also could probably change all the `require.Equal` below to `assert`.

2025-01-10 17:00 UTC, dylanhitt commented on server_test.go
>  	require.Equal(t, document.Paths.Find("/").Get.Parameters[0].Value.Name, "Accept")
This is just a nitpick feel free to resolve

2025-01-12 13:22 UTC, EwenQuim commented
Please rebase your branch on `main`, it is quite outdated :)

Thanks for the PR!

2025-01-13 10:26 UTC, EwenQuim commented
Please fix the tests.

I think you can run `make golden-update` or something like that to update the golden file. But it's weird, it should not change as it is just an internal refactoring

2025-01-14 19:48 UTC, ccoVeille commented on params_test.go
> +			isok := c.QueryParamBool("is_ok")
nitpicking: I would like to suggest

```suggestion
			isOK := c.QueryParamBool("is_ok")
```

2025-01-14 19:48 UTC, ccoVeille commented on params_test.go
> +		require.Equal(t, "integer", route.Params["age"].GoType)
```suggestion
		require.Contains(t, route.Params, "age")
		require.Equal(t, "Age", route.Params["age"].Description)
		require.True(t, route.Params["age"].Nullable)
		require.Equal(t, 18, route.Params["age"].Default)
		require.Equal(t, "integer", route.Params["age"].GoType)
```

Or, maybe you could do this, the readability will be increased

```suggestion
		require.Contains(t, route.Params, "age")
		paramAge := route.Params["age"]
		require.Equal(t, "Age", paramAge.Description)
		require.True(t, paramAge.Nullable)
		require.Equal(t, 18, paramAge.Default)
		require.Equal(t, "integer", paramAge.GoType)
```

2025-01-14 19:48 UTC, ccoVeille commented on params_test.go
> +		require.Equal(t, "string", route.Params["name"].GoType)
This would be safer if something is refactored, it won't panic

```suggestion
		require.Contains(t, route.Params, name)
		require.Equal(t, "Name", route.Params["name"].Description)
		require.True(t, route.Params["name"].Required)
		require.Equal(t, "hey", route.Params["name"].Default)
		require.Contains(t, route.Params["name"].Examples, "example1")
		require.Equal(t, "you", route.Params["name"].Examples["example1"])
		require.Equal(t, "string", route.Params["name"].GoType)
```

2025-01-14 19:48 UTC, ccoVeille commented on params_test.go
> +		require.Equal(t, "string", route.Params["name"].GoType)
Also this would be more readable

```suggestion
		require.Contains(t, route.Params, name)
		paramName := route.Params["name"]
		require.Equal(t, "Name", paramName.Description)
		require.True(t, paramName.Required)
		require.Equal(t, "hey", paramName.Default)
		require.Contains(t, paramName.Examples, "example1")
		require.Equal(t, "you", paramName.Examples["example1"])
		require.Equal(t, "string", paramName.GoType)
```

2025-01-14 19:48 UTC, ccoVeille commented on server_test.go
> +	require.Equal(t, document.Paths.Find("/api/test").Get.Parameters[0].Value.Name, "Accept")
Not related to this PR, but something like this should be added to avoid panics if there is a refactoring 

```suggestion
	require.Len(t, document.Paths.Find("/api/test").Get.Parameters, 2)
	require.Equal(t, document.Paths.Find("/api/test").Get.Parameters[0].Value.Name, "Accept")
```

2025-01-14 19:48 UTC, ccoVeille commented on server_test.go
> +	require.Equal(t, document.Paths.Find("/api/test").Get.Parameters[0].Value.Name, "Accept")
Same about testing Get.Parameters with require.Len

And in the next tests you are updating

2025-01-14 20:51 UTC, ekumamatthew commented
> Please fix the tests.
> 
> I think you can run `make golden-update` or something like that to update the golden file. But it's weird, it should not change as it is just an internal refactoring

![gotMakeTest](https://github.com/user-attachments/assets/7a6ee826-e52c-48a1-bfd6-096536b2e4d0)

2025-01-14 22:02 UTC, dylanhitt commented
https://github.com/go-fuego/fuego/pull/324#issuecomment-2591078417

Is that updating that file for you?

2025-01-14 22:04 UTC, dylanhitt commented
Damn, it isn't. Hmm something is going on here.

2025-01-14 22:05 UTC, dylanhitt commented
Oh nevermind the test s are failing cause their are two functions named TestParams

2025-01-14 22:06 UTC, dylanhitt commented
Also the change to golden is the ordering so that should be fine.

2025-01-19 15:57 UTC, ccoVeille commented
Not, that's a major issue, but I made 5+ feedbacks, and none were addressed, or at least commented.

I would appreciate if they could be reviewed.

Thanks

2025-01-19 16:18 UTC, ekumamatthew commented
i just sync my brnch. i'll be updating my PR shortly

2025-01-20 09:01 UTC, EwenQuim requested changes

2025-01-20 09:01 UTC, EwenQuim commented on server.go
>  	}
Here you're adding the parameter to all routes.

Fuego can also register standard `func(w http.ResponseWriter, r *http.Request)` routes that don't need this option.

I suggest that you move this to the `registerFuegoController()` function in `net_http_mux.go` file

2025-01-29 19:42 UTC, EwenQuim commented
Any news on this @ekumamatthew ?

2025-02-03 16:49 UTC, EwenQuim commented
Closed because #380 has been merged

2025-02-03 16:49 UTC, closed without merging